server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: admin
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    enabled: true
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        type: trace
        ddl-auto: update
        show_sql: true
        use_sql_comments: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
